language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install: sudo apt-get install libxml2-dev libxslt-dev
# command to install dependencies
install:
  - python setup.py install
  - make deps
# command to run tests
script: py.test -q --tb native -s tests
